#!/bin/bash
# DRIVE READY
#
externaldrivepartitiondirpath=/external
#
### Cache Firefox
rm -rf /home/pi/.cache/mozilla/firefox
mkdir -p /home/pi/.cache/mozilla/
chown pi /home/pi/.cache
chown pi /home/pi/.cache/mozilla/
dd if=/dev/zero of=$externaldrivepartitiondirpath/firefoxcache bs=1M count=2048
chmod 0600 $externaldrivepartitiondirpath/firefoxcache
mke2fs -t ext4 -m 0 -F -O ^64bit -L firefoxcache -E lazy_itable_init=0,lazy_journal_init=0 $externaldrivepartitiondirpath/firefoxcache
echo "$externaldrivepartitiondirpath/firefoxcache  /home/pi/.cache/mozilla/         ext4    defaults          0       4" >> /etc/fstab
### Swap file
dd if=/dev/zero of=$externaldrivepartitiondirpath/swapfile bs=1M count=2048
chmod 0600 $externaldrivepartitiondirpath/swapfile
sleep 1
sync
mkswap $externaldrivepartitiondirpath/swapfile
echo "$externaldrivepartitiondirpath/swapfile  none          swap    sw,pri=3          0       0" >> /etc/fstab
mkdir -p /home/pi/.config
chown pi /home/pi/.config
cp -r transmission /home/pi/.config
chown -R pi /home/pi/.config/transmission
sleep 1
sync
sleep 5
reboot
